apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
spec:
  selector:
    matchLabels:
      app: tasks

  template:
    metadata:
      labels:
        app: tasks

    spec:
      containers:
        - name: tasks
          image: wyteng/task1
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: tasksservice
  annotations:
    konghq.com/plugins: 12-per-min
spec:
  type: NodePort
  selector:
    app: tasks
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32500
